import 'package:housytask/user.dart';

const Dummy_electrician = [
  User(
    id: 1,
    company: "Sky Services",
    image: "assets/images/elect1.jpg",
    location: "Morbi, Gujarat",
    name: "Joseph Farnandis",
    price: 80,
    rattings: 4,
    service_id: 2,
    work: 2,
  ),
  User(
    id: 2,
    company: "Sun Services",
    image: "assets/images/elect1.jpg",
    location: "Morbi, Gujarat",
    name: "Raghu Ram",
    price: 100,
    rattings: 5,
    service_id: 2,
    work: 3,
  ),
  User(
    id: 3,
    company: "Ocean Services",
    image: "assets/images/elect1.jpg",
    location: "Morbi, Gujarat",
    name: "Krishna vasudev",
    price: 90,
    rattings: 4,
    service_id: 2,
    work: 2,
  ),
  User(
    id: 4,
    company: "Sky Services",
    image: "assets/images/elect1.jpg",
    location: "Morbi, Gujarat",
    name: "Sanket shah",
    price: 95,
    rattings: 5,
    service_id: 2,
    work: 3,
  ),
  User(
    id: 5,
    company: "Sky Services",
    image: "assets/images/elect1.jpg",
    location: "Morbi, Gujarat",
    name: "Samved shah",
    price: 100,
    rattings: 4,
    service_id: 2,
    work: 2,
  ),
  User(
    id: 6,
    company: "Ocean Services",
    image: "assets/images/elect1.jpg",
    location: "Morbi, Gujarat",
    name: "Sagar Chovatiya",
    price: 200,
    rattings: 4,
    service_id: 2,
    work: 3,
  ),
  User(
    id: 7,
    company: "Sky Services",
    image: "assets/images/elect1.jpg",
    location: "Morbi, Gujarat",
    name: "Jainam Chovatiya",
    price: 120,
    rattings: 5,
    service_id: 2,
    work: 2,
  ),
User(
    id: 8,
    company: "Ocean Services",
    image: "assets/images/elect1.jpg",
    location: "Morbi, Gujarat",
    name: "Savan Matariya",
    price: 140,
    rattings: 4,
    service_id: 2,
    work: 3,
  ),
  User(
    id: 9,
    company: "Sun Services",
    image: "assets/images/elect1.jpg",
    location: "Morbi, Gujarat",
    name: "Krishna vasudev",
    price: 120,
    rattings: 5,
    service_id: 2,
    work: 3,
  ),
  User(
    id: 10,
    company: "Ocean Services",
    image: "assets/images/elect1.jpg",
    location: "Morbi, Gujarat",
    name: "Hasmukh Matariya",
    price: 30,
    rattings: 5,
    service_id: 2,
    work: 2,
  ),
];
